### ISSUE TITLE
[BUG] Cannot find module 'object-assign'

### ISSUE THREAD

**Issue by cenfun** [npm/gauge#123]
# What / Why

UNCAUGHT EXCEPTION - keeping process alive: Error: Cannot find module 'object-assign'
Require stack:
- node_modules\gauge\theme-set.js
- node_modules\gauge\themes.js
- node_modules\gauge\index.js

"object-assign" should be added to package.json dependencies

**Comment by stevenvachon** [comment]
Almost a year and no comment from the authors

**Comment by matz3** [comment]
Seems to be solved via https://github.com/npm/gauge/commit/45b1c5ff5bdc771b8b5b28c1df190d49c65ceb33 (v3.0.1)
