### ISSUE TITLE
Temporary files on npm release

### ISSUE THREAD

**Issue by talend-glorieux** [npm/gauge#63]
Hi Rebecca,

I was surprised to find that the latest npm release (2.6.0) contains temporary files :

```
-rw-rw-r-- 1 glorieux glorieux  395 Jun 16 03:59 base-theme.js
-rw-rw-r-- 1 glorieux glorieux 5.4K Jun 16 10:55 CHANGELOG.md
-rw-rw-r-- 1 glorieux glorieux 5.0K Jun 16 06:18 CHANGELOG.md~
-rw-rw-r-- 1 glorieux glorieux  616 Jun 16 03:59 error.js
-rw-rw-r-- 1 glorieux glorieux  292 Jun 16 03:59 has-color.js
-rw-rw-r-- 1 glorieux glorieux 6.7K Jun 16 10:52 index.js
-rw-rw-r-- 1 glorieux glorieux  751 Jan 25  2015 LICENSE
-rw-rw-r-- 1 glorieux glorieux 3.0K Jul  6 10:33 package.json
-rw-rw-r-- 1 glorieux glorieux 1.2K Jun 16 03:59 plumbing.js
-rw-rw-r-- 1 glorieux glorieux   89 Jun 16 03:59 process.js
-rw-rw-r-- 1 glorieux glorieux  998 Jun 16 03:59 progress-bar.js
-rw-rw-r-- 1 glorieux glorieux  15K Jun 16 10:53 README.md
-rw-rw-r-- 1 glorieux glorieux  15K Jun 16 06:12 README.md~
-rw-rw-r-- 1 glorieux glorieux 5.7K Jun 16 10:51 render-template.js
-rw-rw-r-- 1 glorieux glorieux  139 Jun 16 03:59 set-immediate.js
-rw-rw-r-- 1 glorieux glorieux   93 Jun 16 03:59 set-interval.js
-rw-rw-r-- 1 glorieux glorieux  105 Jun 16 03:59 spin.js
-rw-rw-r-- 1 glorieux glorieux 1.9K Jun 16 03:59 template-item.js
-rw-rw-r-- 1 glorieux glorieux 3.7K Jun 16 03:59 theme-set.js
-rw-rw-r-- 1 glorieux glorieux 1.6K Jun 16 03:59 themes.js
-rw-rw-r-- 1 glorieux glorieux  828 Jun 16 03:59 wide-truncate.js
```

Looks like leftovers from the release :wink:

**Comment by iarna** [comment]
Yeah grr, that's one of my biggest pet peaves about npm that I can't actually fix. =D

So, for files that are A) ALWAYS included and B) matched with a glob, (examples are: readme, changelog, license) match ALL files that match those names, case insensitively, including anything after that bit in their name. As such, `~` files are included even when you have them in your `ignore` files (or don't mention them in your `files` stanza). The only solution is to manually clean them up before publishing.

Uhm... I should just add a `prepublish` script to do that actually. =D

**Comment by talend-glorieux** [comment]
You can also use an .npmignore file to prevent the files you don't want to be published.
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by iarna** [comment]
@talend-glorieux Yes, but my point is that it doesn't apply to always-included files. =) And `README*` is always included. TBH I'm not sure if we actually document that anywhere, but that's how it is.

¯\_(ツ)_/¯

**Comment by iarna** [comment]
`prepublish` added with 61fa9cf
