### ISSUE TITLE
gauge erasing last line of output in npm

### ISSUE THREAD

**Issue by timoxley** [npm/gauge#9]
The issue in https://github.com/npm/npm/issues/9682 appears to be something to do with gauge AFAICT. The output of the npm command is correct, it just doesn't appear in the terminal because the line is erased. :(

I had a poke around but I'm unclear what the exact issue is.

Removing the `this.cursor.horizontalAbsolute(0).eraseLine()` line from gauge's `.hide` stops the last line from being erased (though output is understandably broken due to lingering gauges).

``` js
ProgressBar.prototype.hide = function() {
  if (!isTTY()) return
  if (this.disabled) return
  this.cursor.show()
  if (this.showing) this.cursor.up(1)
  this.cursor.horizontalAbsolute(0).eraseLine() // remove this and the last line is not erased
  this.showing = false
}
```

[Source](https://github.com/iarna/gauge/blob/9f7eeeeed3b74a70f30b721d570435f6ffbc0168/progress-bar.js#L103)

Perhaps it needs to do something like this? NFI though.
https://github.com/TooTallNate/ansi.js/blob/master/examples/progress/index.js#L38-L45

**Comment by iarna** [comment]
Yeah, soo, the theory was that I was hoping to not have things written to stdout (instead of via `npmlog`) not step on the progressbar, but the result was worse.
I have a rewrite in progress that uses no cursor up commands and just uses a CR.

I'm going to close this, because you'll definitely see a fix for this in the next release (which is getting very close– it's feature complete and I'm just bringing up the test coverage now.)

**Comment by iarna** [comment]
(The branch with lots of unsquashed wip commits is here, incidentally: https://github.com/iarna/gauge/tree/new-rewrite)

**Comment by whitlockjc** [comment]
I know this is closed but for my on sanity, can you let me know if [this garbled output](https://github.com/npm/npm/issues/9670#issuecomment-172007486) could be related to this issue?  I've tried different terminal environments, different fonts and a few other settings but I am unable to get npm on OS X 10.x to not produce one line per gauge state change.

**Comment by iarna** [comment]
Your issue is almost certainly that you have "Treat ambiguous-width characters as double width" enabled. Try disabling this and it should work fine.

**Comment by whitlockjc** [comment]
But I'm not using iTerm so that setting is not available.  The closest setting I can find in Terminal.app is already unchecked.  That's why I came here.  I've tried everything that was suggested in that thread.  I'll do another read and see if I missed something.

**Comment by whitlockjc** [comment]
I just tried the same in iTerm, default profile.  That setting was already disabled.  I've tried different fonts, different size fonts, messing with the display settings, etc.
